version: '2.2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - E:\docker\data\mysql:/var/lib/mysql
  # zookeeper:
  #   image: zookeeper
  #   ports:
  #     - "2181:2181"
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"